[template]
description = "Branch through (to down)"

[simulation]

[simulation.enters]
section = "Branch"

[[simulation.point]]
tiploc = "KMTHHLT"
plat = 1
stop_pct = 75.0
dwell = "0H"

[[simulation.point]]
tiploc = "KESTBY"
plat = 3
dwell = "3"
activities = ["reverse"]

[[simulation.point]]
path = "DM"

[simulation.exits]