[profile]
description = "Class 185 DMU"
units = ["Class185"]

[[segment]]
route = "DM_6:UM_1"
stop = "4"
pass = "3"

[[segment]]
route = "UM_1:KESTBY"
stop = "3"
pass = "2"

[[segment]]
route = "DM_6:KESTBY"
stop = "3"
pass = "2"

[[segment]]
route = "Branch:KMTHHLT"
stop = "2"
pass = "1"

[[segment]]
route = "Branch:KESTBY"
stop = "2"
pass = "1"

[[segment]]
route = "KMTHHLT:KESTBY"
stop = "2"
pass = "1"

[[segment]]
route = "KESTBY:KSBYSDG"
stop = "2"
pass = "1H"

[[segment]]
route = "KESTBY:KSTBY28"
stop = "1"
pass = "1"

[[segment]]
route = "KESTBY:KSTBY29"
stop = "1"
pass = "1"

[[segment]]
route = "KSTBY29:KSBYSDG"
stop = "2"
pass = "1H"

[[segment]]
route = "UM_1:KSTBY29"
stop = "2H"
pass = "2"

[[segment]]
route = "UM_1:KSBYSDG"
stop = "2H"
pass = "2"

[[segment]]
route = "DM_6:KSTBY28"
stop = "2H"
pass = "2"

[[segment]]
route = "Branch:KSTBY29"
stop = "2"
pass = "1"

[[segment]]
route = "Branch:KSBYSDG"
stop = "2"
pass = "1"

[[segment]]
route = "KMTHHLT:KSTBY28"
stop = "2"
pass = "1"

[[segment]]
route = "KMTHHLT:KSTBY29"
stop = "2"
pass = "1"

[[segment]]
route = "KMTHHLT:KSBYSDG"
stop = "2"
pass = "1"