[template]
description = "Branch through (up)"

[static]
template = "AireboroughToBarnardCastle"

[simulation]

[simulation.enters]
section = "UM_1"

[[simulation.point]]
tiploc = "KESTBY"
plat = 3
dwell = "3"
activities = ["reverse"]

[[simulation.point]]
tiploc = "KMTHHLT"
plat = 1
stop_pct = 75.0
path = "DB"
dwell = "0H"

[simulation.exits]