[connections]
AAS = ["ANC", "ANE"]
ANC = ["AAS", "ABH"]
ABH = ["ANC", "PLW", "WYN"]
PLW = ["ABH", "KTW"]
KTW = ["PLW", "BGL", "NTR"]
BGL = ["KTW", "STL"]
STL = ["BGL", "BSP"]
BSP = ["STL", "BRW"]
BRW = ["BSP", "FLR"]
FLR = ["BRW", "WRW"]
WRW = ["FLR", "GPT"]
ANE = ["AAS", "NWC"]
NWC = ["ANE", "CTN"]
CTN = ["NWC", "HPB"]
HPB = ["CTN", "SLW"]
SLW = ["HPB", "FBR"]
FBR = ["SLW", "HSM"]
HSM = ["FBR", "KBY"]
KBY = ["HSM", "BWK", "KMH"]
BWK = ["KBY", "CLM"]
CLM = ["BWK", "HMB"]
HMB = ["CLM", "CKS"]
CKS = ["HMB", "MTF"]
MTF = ["CKS", "SBR"]
SBR = ["MTF", "AIB"]
AIB = ["SBR"]
WYN = ["ABH", "SLT"]
SLT = ["WYN", "DNF"]
DNF = ["SLT", "BTL"]
BTL = ["DNF", "BOS"]
BOS = ["BTL"]
NTR = ["KTW"]
KMH = ["KBY", "WGL"]
WGL = ["KMH", "STE"]
STE = ["WGL", "ELD"]
ELD = ["STE", "BNC"]
BNC = ["ELD", "BBR"]
BBR = ["BNC", "HFD"]
HFD = ["BBR", "LPT"]
LPT = ["HFD", "GPT"]
GPT = ["LPT", "WRW"]

[[unmodelled]]
at = "MTF"
weight = 1.0

[[unmodelled]]
at = "AIB"
weight = 1.0