[template]
description = "Bluewall-on-sea to Anserham"
operator = "TransPennine Express"

[static]
BOS = { dep = "0" }
KBY = { sim = true }
HSM = { arr = "24", dep = "24H" }
SLW = { arr = "31", dep = "31H" }
ANS = { arr = "39" }

[simulation]

[simulation.enters]
section = "Branch"
time = "13H"

[[simulation.point]]
tiploc = "KMTHHLT"
dep = "14"
plat = 1
pass = true

[[simulation.point]]
tiploc = "KESTBY"
arr = "16"
dep = "16H"
plat = 1

[simulation.exits]