[template]
description = "Anserham to Bluewall-on-sea"
operator = "TransPennine Express"

[static]
ANS = { dep = "0" }
SLW = { arr = "8", dep = "8H" }
HSM = { arr = "15", dep = "15H" }
KBY = { sim = true }
BOS = { arr = "40" }

[simulation]

[simulation.enters]
section = "DM_6"
time = "21H"

[[simulation.point]]
tiploc = "KESTBY"
arr = "23H"
dep = "24"
plat = 2

[[simulation.point]]
tiploc = "KMTHHLT"
dep = "26"
plat = 1
pass = true
path = "DB"

[simulation.exits]