[template]
description = "Anserham to Aireborough"
operator = "TransPennine Express"

[static]
ANS = { dep = "0" }
SLW = { arr = "8", dep = "8H" }
HSM = { arr = "15", dep = "15H" }
CLM = { arr = "26", dep = "26H" }
MFT = { arr = "33", dep = "33H" }
AIR = { arr = "38" }

[simulation]

[simulation.enters]
section = "DM_6"
time = "18H"

[[simulation.point]]
tiploc = "KESTBY"
pass = true
dep = "20H"
plat = 2

[simulation.exits]