[template]
description = "Anserham to Bluewall-on-sea"
operator = "Northern"

[static]
ANS = { dep = "0" }
ANE = { arr = "3", dep = "3H" }
HBF = { arr = "7", dep = "7H" }
SLW = { arr = "12", dep = "12H" }
FBD = { arr = "17", dep = "17H" }
HSM = { arr = "22", dep = "22H" }
KBY = { sim = true }
KMH = { sim = true }
SHM = { arr = "37", dep = "37H" }
DFD = { arr = "42", dep = "42H" }
BLE = { arr = "47", dep = "47H" }
BOS = { arr = "55" }

[simulation]

[simulation.enters]
section = "DM_6"
time = "25"

[[simulation.point]]
tiploc = "KESTBY"
arr = "28"
dep = "28H"
plat = 3

[[simulation.point]]
tiploc = "KMTHHLT"
arr = "32"
dep = "33"
plat = 1
stop_pct = 65.0

[simulation.exits]