[template]
description = "Kestby to Bluewall-on-sea"
operator = "Northern"

[static]
KMH = { sim = true }
KBY = { sim = true }
BOS = { arr = "9", dep = "9H"}
BLE = { arr = "14", dep = "14H" }
DFD = { arr = "18H",  dep = "19" }
SHM = { arr = "24" }

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
dep = "0"
plat = 3
activities = ["reverse"]

[[simulation.point]]
tiploc     = "KMTHHLT"
arr        = "2H"
dep        = "3"
plat       = 1
stop_pct   = 40.0
path = "DB"

[simulation.exits]