[template]
description = "Anserham to Aireborough"
operator = "Northern"

[static]
ANS = { dep = "0" }
ANE = { arr = "3", dep = "3H" }
HBF = { arr = "7", dep = "7H" }
SLW = { arr = "12", dep = "12H" }
FBD = { arr = "17", dep = "17H" }
HSM = { arr = "22", dep = "22H" }
KBY = { sim = true }
BRW = { arr = "32", dep = "32H" }
CLM = { arr = "37", dep = "37H" }
HBY = { arr = "42", dep = "42H" }
CST = { arr = "47", dep = "47H" }
MFT = { arr = "52", dep = "52H" }
AIR = { arr = "58" }

[simulation]

[simulation.enters]
section = "DM_6"
time = "25"

[[simulation.point]]
tiploc = "KESTBY"
arr = "27"
dep = "27H"
plat = 2

[simulation.exits]