[template]
description = "Aireborough to Anserham"
operator = "TransPennine Express"

[static]
AIR = { dep = "0" }
MFT = { arr = "6", dep = "6H" }
CST = { arr = "11", dep = "11H" }
HBY = { arr = "16", dep = "16H" }
CLM = { arr = "21", dep = "21H" }
BRW = { arr = "26", dep = "26H" }
KBY = { sim = true }
HSM = { arr = "36", dep = "36H" }
FBD = { arr = "41", dep = "41H" }
SLW = { arr = "46", dep = "46H" }
HBF = { arr = "51", dep = "51H" }
ANS = { arr = "57" }

[simulation]

[simulation.enters]
section = "UM_1"
time = "29"

[[simulation.point]]
tiploc = "KESTBY"
arr = "31"
dep = "31H"
plat = 1

[simulation.exits]