[template]
description = "Branch shuttle (down)"

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
plat = 3

[[simulation.point]]
tiploc = "KMTHHLT"
plat = 1
stop_pct = 75.0
path = "DB"
dwell = "0H"

[simulation.exits]