[template]
description = "ECS Kestby Sidings to Kestby P2"

[simulation]

[[simulation.point]]
tiploc = "KSBYSDG"
dep = "0H"

[[simulation.point]]
tiploc = "KSTBY29"
arr = "1H"
dep = "3"
activities = ["reverse"]

[[simulation.point]]
tiploc = "KESTBY"
arr = "4"
plat = 2

[simulation.terminates]