[template]
description = "ECS Kestby P1 to Kestby Sidings"

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
dep = "0H"
plat = 1

[[simulation.point]]
tiploc = "KSTBY29"
arr = "1"
dep = "3"
activities = ["reverse"]

[[simulation.point]]
tiploc = "KSBYSDG"
arr = "4H"

[simulation.terminates]