[template]
description = "Kestby stopper (up)"

[simulation]

[simulation.enters]
section = "UM_1"

[[simulation.point]]
tiploc = "KESTBY"
plat = 1
dwell = "1"
activities = [
    { type = "detach", id = "branch_shuttle_detach" },
]

[[simulation.point]]
path = "UM"

[simulation.exits]