[template]
description = "Terminator down from kestby"

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
plat = 2
activities = [
    { type = "attach", id = "branch_shuttle_attach" },
]

[[simulation.point]]
path = "DM"

[simulation.exits]