[diagram]
allocation = [
    { consist = "156", weight = 50 },
    { consist = "158", weight = 30 },
    { consist = "142", weight = 20 },
]

set_swap_pool = [
    { consist = "156", weight = 50 },
    { consist = "158", weight = 25 },
    { consist = "142", weight = 20 },
    { consist = "150", weight = 5 }
]

[scenario]
base_delay = 4
delayed_pct = 0.30
disruption_pct = 0.10
set_swap_pct = 0.10

[[service]]
headcode = "2N02"
template = "2N-in"
departs = "0530"

[[service]]
headcode = "2N04"
template = "2N-out"
departs = "0645"

[[service]]
headcode = "2N06"
template = "2N-in"
departs = "0752"

[[service]]
headcode = "2N08"
template = "2N-out"
departs = "0907"

[[service]]
headcode = "2N10"
template = "2N-in"
departs = "1014"

[[service]]
headcode = "2N11"
template = "2N-out"
departs = "1129"

[[service]]
headcode = "2N13"
template = "2N-in"
departs = "1236"

[[service]]
headcode = "2N15"
template = "2N-out"
departs = "1351"

[[service]]
headcode = "2N17"
template = "2N-in"
departs = "1458"

[[service]]
headcode = "2N20"
template = "2N-out"
departs = "1613"

[[service]]
headcode = "2N22"
template = "2N-in"
departs = "1731"

[[service]]
headcode = "2N24"
template = "2N-out"
departs = "1846"

[[service]]
headcode = "2N26"
template = "2N-in"
departs = "1949"