[diagram]
allocation = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 },
    { consist = "2x150", weight = 13 },
    { consist = "2x156", weight = 12 },
]
set_swap_pool = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 },
    { consist = "2x150", weight = 13 },
    { consist = "2x156", weight = 12 },
]

[scenario]
base_delay = 3
delayed_pct = 0.17
disruption_pct = 0.05
set_swap_pct = 0.09

[[service]]
headcode = "2K04"
template = "TerminatorDown"
departs = "0637"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K05"
template = "TerminatorUpFromKestby"
departs = "0730"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K11"
template = "TerminatorDown"
departs = "0937"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K12"
template = "TerminatorUpFromKestby"
departs = "1000"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K21"
template = "TerminatorDown"
departs = "1207"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K22"
template = "TerminatorUpFromKestby"
departs = "1230"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K31"
template = "TerminatorDown"
departs = "1437"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K32"
template = "TerminatorUpFromKestby"
departs = "1500"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K41"
template = "TerminatorDown"
departs = "1707"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K42"
template = "TerminatorUpFromKestby"
departs = "1730"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K48"
template = "TerminatorDown"
departs = "1937"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K51"
template = "TerminatorUpFromKestby"
departs = "2130"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2N16"
template = "BranchThroughFromDown"
departs = "0007"
[service.static]
template = "KestbyTerminatorExtended"
