[diagram]
operator = "Northern"
allocation = [
    { consist = "150", weight = 40 },
    { consist = "142", weight = 35 }
]
set_swap_pool = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 }
]

[scenario]
base_delay = 2
delayed_pct = 0.13
disruption_pct = 0.03
set_swap_pct = 0.08

[[service]]
headcode = "2K06"
template = "TerminatorDown"
departs = "0737"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K07"
template = "TerminatorUpFromKestby"
departs = "0830"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K15"
template = "TerminatorDown"
departs = "1037"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K16"
template = "TerminatorUpFromKestby"
departs = "1100"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K25"
template = "TerminatorDown"
departs = "1307"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K26"
template = "TerminatorUpFromKestby"
departs = "1330"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K35"
template = "TerminatorDown"
departs = "1537"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K36"
template = "TerminatorUpFromKestby"
departs = "1600"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K44"
template = "TerminatorDown"
departs = "1807"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K47"
template = "TerminatorUpFromKestby"
departs = "1930"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K52"
template = "TerminatorDown"
departs = "2137"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K55"
template = "TerminatorUpFromKestby"
departs = "2330"
[service.static]
template = "KestbyTerminator"
reversed = true
