[diagram]
operator = "Northern"
allocation = [
    { consist = "150", weight = 40 },
    { consist = "142", weight = 35 }
]
set_swap_pool = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 }
]

[scenario]
base_delay = 2
delayed_pct = 0.15
disruption_pct = 0.03
set_swap_pct = 0.08

[[service]]
headcode = "2K01"
template = "TerminatorUpFromKestby"
departs = "0530"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2N01"
template = "BranchThroughFromDown"
departs = "0707"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2N04"
template = "BranchThroughToDown"
departs = "0815"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true

[[service]]
headcode = "2K13"
template = "TerminatorDown"
departs = "1007"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K14"
template = "TerminatorUpFromKestby"
departs = "1030"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K23"
template = "TerminatorDown"
departs = "1237"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K24"
template = "TerminatorUpFromKestby"
departs = "1300"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K33"
template = "TerminatorDown"
departs = "1507"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K34"
template = "TerminatorUpFromKestby"
departs = "1530"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K43"
template = "TerminatorDown"
departs = "1737"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K45"
template = "TerminatorUpFromKestby"
departs = "1830"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K50"
template = "TerminatorDown"
departs = "2037"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K53"
template = "TerminatorUpFromKestby"
departs = "2230"
[service.static]
template = "KestbyTerminator"
reversed = true
