[diagram]
operator = "Northern"
allocation = [
    { consist = "150", weight = 40 },
    { consist = "142", weight = 35 }
]
set_swap_pool = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 }
]

[scenario]
base_delay = 2
delayed_pct = 0.14
disruption_pct = 0.04
set_swap_pct = 0.09

[[service]]
headcode = "2K02"
template = "TerminatorDown"
departs = "0900"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2K03"
template = "TerminatorUpFromKestby"
departs = "0932"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true

[[service]]
headcode = "2K04"
template = "TerminatorDown"
departs = "1005"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K05"
template = "TerminatorUpFromKestby"
departs = "1033"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K06"
template = "TerminatorDown"
departs = "1101"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K07"
template = "TerminatorUpFromKestby"
departs = "1129"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K08"
template = "TerminatorDown"
departs = "1157"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K09"
template = "TerminatorUpFromKestby"
departs = "1225"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K10"
template = "TerminatorDown"
departs = "1253"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K11"
template = "TerminatorUpFromKestby"
departs = "1321"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K12"
template = "TerminatorDown"
departs = "1349"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2K13"
template = "TerminatorUpFromKestby"
departs = "1422"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true

[[service]]
headcode = "2K14"
template = "TerminatorDown"
departs = "1454"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K15"
template = "TerminatorUpFromKestby"
departs = "1522"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K16"
template = "TerminatorDown"
departs = "1550"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K17"
template = "TerminatorUpFromKestby"
departs = "1618"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K18"
template = "TerminatorDown"
departs = "1646"
[service.static]
template = "KestbyTerminator"

[[service]]
headcode = "2K19"
template = "TerminatorUpFromKestby"
departs = "1714"
[service.static]
template = "KestbyTerminator"
reversed = true

[[service]]
headcode = "2K20"
template = "TerminatorDown"
departs = "1742"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2K21"
template = "TerminatorUpFromKestby"
departs = "1814"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true