[diagram]
operator = "Northern"
allocation = [
    { consist = "150", weight = 40 },
    { consist = "142", weight = 35 }
]
set_swap_pool = [
    { consist = "150", weight = 40 },
    { consist = "156", weight = 35 }
]

[scenario]
base_delay = 2
delayed_pct = 0.15
disruption_pct = 0.04
set_swap_pct = 0.08

[[service]]
headcode = "2N02"
template = "BranchThroughToDown"
departs = "0715"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true

[[service]]
headcode = "2N05"
template = "BranchThroughFromDown"
departs = "0907"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2N08"
template = "BranchThroughToDown"
departs = "1915"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true

[[service]]
headcode = "2N11"
template = "BranchThroughFromDown"
departs = "2107"
[service.static]
template = "KestbyTerminatorExtended"

[[service]]
headcode = "2N14"
template = "BranchThroughToDown"
departs = "2215"
[service.static]
template = "KestbyTerminatorExtended"
reversed = true
