[diagram]
allocation = [
    { consist = "156", weight = 55 },
    { consist = "158", weight = 45 },
]
set_swap_pool = [
    { consist = "156", weight = 55 },
    { consist = "158", weight = 45 },
]

[scenario]
base_delay = 4
delayed_pct = 0.23
disruption_pct = 0.07
set_swap_pct = 0.05

[[service]]
headcode = "2J04"
template = "BranchThroughFromDown"
departs = "1057"
[service.static]
template = "BarnardBranchThrough"

[[service]]
headcode = "2J09"
template = "BranchThroughToDown"
departs = "1527"
[service.static]
template = "BarnardBranchThrough"
reversed = true

[[service]]
headcode = "2J12"
template = "BranchThroughFromDown"
departs = "1857"
[service.static]
template = "BarnardBranchThrough"
