[diagram]
operator = "Northern"
allocation = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]
set_swap_pool = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]

[scenario]
base_delay = 3
delayed_pct = 0.2
disruption_pct = 0.05
set_swap_pct = 0.05

[[service]]
headcode = "2A03"
template = "StopperDown"
departs = "0642"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A06"
template = "StopperUp"
departs = "0817"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C08"
template = "StopperDown"
departs = "1012"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C15"
template = "StopperUp"
departs = "1322"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A18"
template = "StopperDown"
departs = "1542"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A20"
template = "StopperUp"
departs = "1717"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C26"
template = "StopperDown"
departs = "1912"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C33"
template = "StopperUp"
departs = "2222"
[service.static]
template = "StopperBluewall"
reversed = true
