[diagram]
allocation = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]
set_swap_pool = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]

[scenario]
base_delay = 3
delayed_pct = 0.21
disruption_pct = 0.05
set_swap_pct = 0.06

[[service]]
headcode = "2C01"
template = "StopperDown"
departs = "0612"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C07"
template = "StopperUp"
departs = "0922"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A11"
template = "StopperDown"
departs = "1142"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A14"
template = "StopperUp"
departs = "1317"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C18"
template = "StopperDown"
departs = "1512"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C25"
template = "StopperUp"
departs = "1822"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A27"
template = "StopperDown"
departs = "2042"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A30"
template = "StopperUp"
departs = "2217"
[service.static]
template = "StopperAgincourt"
reversed = true
