[diagram]
operator = "Northern"
allocation = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
    { diagram = "NT222" },
]
set_swap_pool = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]

[scenario]
base_delay = 4
delayed_pct = 0.22
disruption_pct = 0.06
set_swap_pct = 0.07

[[service]]
headcode = "2A02"
template = "StopperUp"
departs = "0617"
[service.static]
template = "StopperAgincourt"
reversed = true
[service.activity.branch_shuttle_detach]
forms = "5F01"
detach_diagram = "NT222"

[[service]]
headcode = "2C04"
template = "StopperDown"
departs = "0812"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C11"
template = "StopperUp"
departs = "1122"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A15"
template = "StopperDown"
departs = "1342"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A17"
template = "StopperUp"
departs = "1517"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C22"
template = "StopperDown"
departs = "1712"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C29"
template = "StopperUp"
departs = "2022"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A31"
template = "StopperDown"
departs = "2242"
[service.static]
template = "StopperAgincourt"
