[diagram]
allocation = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]
set_swap_pool = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]

[scenario]
base_delay = 3
delayed_pct = 0.19
disruption_pct = 0.05
set_swap_pct = 0.05

[[service]]
headcode = "2A01"
template = "StopperDown"
departs = "0542"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A04"
template = "StopperUp"
departs = "0717"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C06"
template = "StopperDown"
departs = "0912"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C13"
template = "StopperUp"
departs = "1222"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2B03"
template = "StopperDown"
departs = "1442"
[service.static]
template = "StopperNewtonRoad"
