[diagram]
allocation = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]
set_swap_pool = [
    { consist = "156", weight = 60 },
    { consist = "158", weight = 40 },
]

[scenario]
base_delay = 3
delayed_pct = 0.2
disruption_pct = 0.05
set_swap_pct = 0.06

[[service]]
headcode = "2B02"
template = "StopperUp"
departs = "1039"
[service.static]
template = "StopperNewtonRoad"
reversed = true

[[service]]
headcode = "2A13"
template = "StopperDown"
departs = "1242"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A16"
template = "StopperUp"
departs = "1417"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2C20"
template = "StopperDown"
departs = "1612"
[service.static]
template = "StopperBluewall"

[[service]]
headcode = "2C27"
template = "StopperUp"
departs = "1922"
[service.static]
template = "StopperBluewall"
reversed = true

[[service]]
headcode = "2A29"
template = "StopperDown"
departs = "2142"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A32"
template = "StopperUp"
departs = "2317"
[service.static]
template = "StopperAgincourt"
reversed = true

[[service]]
headcode = "2A33"
template = "StopperDown"
departs = "2342"
[service.static]
template = "StopperAgincourt"

[[service]]
headcode = "2A34"
template = "StopperUp"
departs = "0017"
[service.static]
template = "StopperAgincourt"
reversed = true
