[diagram]
allocation = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

set_swap_pool = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

[scenario]
base_delay = 4
delayed_pct = 0.30
disruption_pct = 0.10
set_swap_pct = 0.10

[[service]]
headcode = "2T04"
template = "2T-in"
departs = "0924"

[[service]]
headcode = "2T07"
template = "2T-out"
departs = "1034"

[[service]]
headcode = "2T10"
template = "2T-in"
departs = "1224"

[[service]]
headcode = "2T13"
template = "2T-out"
departs = "1334"

[[service]]
headcode = "2T16"
template = "2T-in"
departs = "1524"

[[service]]
headcode = "2T19"
template = "2T-out"
departs = "1634"

[[service]]
headcode = "2T22"
template = "2T-in"
departs = "1824"

[[service]]
headcode = "2T25"
template = "2T-out"
departs = "1934"

[[service]]
headcode = "2T28"
template = "2T-in"
departs = "2124"