[diagram]
allocation = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

set_swap_pool = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

[scenario]
base_delay = 4
delayed_pct = 0.30
disruption_pct = 0.10
set_swap_pct = 0.10

[[service]]
headcode = "2T01"
template = "2T-in"
departs = "0724"

[[service]]
headcode = "2T03"
template = "2T-out"
departs = "0834"

[[service]]
headcode = "2T06"
template = "2T-in"
departs = "1024"

[[service]]
headcode = "2T09"
template = "2T-out"
departs = "1134"

[[service]]
headcode = "2T12"
template = "2T-in"
departs = "1324"

[[service]]
headcode = "2T15"
template = "2T-out"
departs = "1434"

[[service]]
headcode = "2T18"
template = "2T-in"
departs = "1624"

[[service]]
headcode = "2T21"
template = "2T-out"
departs = "1734"

[[service]]
headcode = "2T24"
template = "2T-in"
departs = "1924"

[[service]]
headcode = "2T27"
template = "2T-out"
departs = "2034"