[diagram]
allocation = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

set_swap_pool = [
    { consist = "185", weight = 50 },
    { consist = "2x185", weight = 50 },
]

[scenario]
base_delay = 4
delayed_pct = 0.30
disruption_pct = 0.10
set_swap_pct = 0.10

[[service]]
headcode = "1B01"
template = "1B-out"
departs = "0618"

[[service]]
headcode = "1B02"
template = "1B-in"
departs = "0712"

[[service]]
headcode = "1B03"
template = "1B-out"
departs = "0818"

[[service]]
headcode = "1B04"
template = "1B-in"
departs = "0912"

[[service]]
headcode = "1B05"
template = "1B-out"
departs = "1018"

[[service]]
headcode = "1B06"
template = "1B-in"
departs = "1112"

[[service]]
headcode = "1B07"
template = "1B-out"
departs = "1218"

[[service]]
headcode = "1B08"
template = "1B-in"
departs = "1312"

[[service]]
headcode = "1B09"
template = "1B-out"
departs = "1418"

[[service]]
headcode = "1B10"
template = "1B-in"
departs = "1512"

[[service]]
headcode = "1B11"
template = "1B-out"
departs = "1618"

[[service]]
headcode = "1B12"
template = "1B-in"
departs = "1712"

[[service]]
headcode = "1B13"
template = "1B-out"
departs = "1818"

[[service]]
headcode = "1B14"
template = "1B-in"
departs = "1912"

[[service]]
headcode = "1B15"
template = "1B-out"
departs = "2018"

[[service]]
headcode = "1B16"
template = "1B-in"
departs = "2112"