[diagram]
allocation = [
    { consist = "185", weight = 75 },
    { consist = "2x185", weight = 25 },
]
set_swap_pool = [
    { consist = "185", weight = 75 },
    { consist = "2x185", weight = 25 },
]

[scenario]
base_delay = 4
delayed_pct = 0.22
disruption_pct = 0.06
set_swap_pct = 0.04

[[service]]
headcode = "1T05"
template = "FastDown"
departs = "0811"
[service.static]
template = "TPEFast"

[[service]]
headcode = "1T08"
template = "FastUp"
departs = "0929"
[service.static]
template = "TPEFast"
reversed = true

[[service]]
headcode = "1T11"
template = "FastDown"
departs = "1035"
[service.static]
template = "TPEFast"

[[service]]
headcode = "2T11"
template = "StopperUp"
departs = "1202"
[service.static]
template = "TPESemifast"
reversed = true

[[service]]
headcode = "2T14"
template = "StopperDown"
departs = "1307"
[service.static]
template = "TPESemifast"

[[service]]
headcode = "1T18"
template = "FastUp"
departs = "1429"
[service.static]
template = "TPEFast"
reversed = true

[[service]]
headcode = "1T21"
template = "FastDown"
departs = "1535"
[service.static]
template = "TPEFast"

[[service]]
headcode = "2T21"
template = "StopperUp"
departs = "1702"
[service.static]
template = "TPESemifast"
reversed = true

[[service]]
headcode = "2T24"
template = "StopperDown"
departs = "1807"
[service.static]
template = "TPESemifast"

[[service]]
headcode = "2T25"
template = "StopperUp"
departs = "1902"
[service.static]
template = "TPESemifast"
reversed = true

[[service]]
headcode = "1T32"
template = "FastDown"
departs = "2035"
[service.static]
template = "TPEFast"

[[service]]
headcode = "1T33"
template = "FastUp"
departs = "2129"
[service.static]
template = "TPEFast"
reversed = true
